---
- name: Setup
  hosts: all
  become: yes

  vars_files:
    - vars/setup.yml

  pre_tasks:
    - name: Install the official MySQL repo
      apt:
        deb: https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
        state: present
    - name: install python mysql bindings
      apt: name=python-mysqldb state=installed
    - name: Install build dependencies
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - build-essential
        - unzip

  roles:
    - oefenweb.swapfile
    - geerlingguy.docker
    - geerlingguy.git
    - geerlingguy.nginx
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.memcached
    - geerlingguy.mysql
    - geerlingguy.mailhog
    - geerlingguy.postgresql
    - geerlingguy.redis
    - stephdewit.nvm
    - cowops.debian-beanstalkd
    - ypsman.aws_cli

