---
- name: Setup
  hosts: all
  become: yes

  vars_files:
    - vars/setup.yml
    - vars/nginx-hosts.yml

  pre_tasks:
    - name: Install the official MySQL repo
      apt:
        deb: https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
        state: present
    - name: Install build dependencies
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - python-mysqldb
        - build-essential
        - unzip
    - name: Enable passwordless sudo for sudo group
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

  roles:
    - oefenweb.swapfile
    - geerlingguy.docker
    - geerlingguy.git
    - geerlingguy.nginx
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.memcached
    - geerlingguy.mysql
    - geerlingguy.mailhog
    - geerlingguy.postgresql
    - geerlingguy.redis
    - stephdewit.nvm
    - cowops.debian-beanstalkd
    - ypsman.aws_cli
    - setup_dotfiles


