---
- name: Checkout
  hosts: all

  vars_files:
    - vars/config.yml

  tasks:
    - name: Create workspace folder in users home directory
      file:
        path: "{{ ansible_user_dir }}/workspace"
        state: directory
    - name: Create .gpg folder in users home directory
      file:
        path: "{{ ansible_user_dir }}/.gpg"
        state: directory
    - name: Copy ssh keys
      copy:
        src: "{{ checkout_ssh_keys_root_dir }}/{{ item }}"
        dest: "{{ ansible_user_dir }}/.ssh/{{ item }}"
        mode: 0600
      with_items: "{{ checkout_ssh_keys }}"
    - name: Copy gpg keys
      copy:
        src: "{{ checkout_gpg_keys_root_dir }}/{{ item }}"
        dest: "{{ ansible_user_dir }}/.gpg/{{ item }}"
        mode: 0600
      with_items: "{{ checkout_gpg_keys }}"
    - name: Set git user.name
      git_config:
        name: user.name
        scope: global
        value: "{{ git_user_name }}"
    - name: Set git user.email
      git_config:
        name: user.email
        scope: global
        value: "{{ git_user_email }}"
    - name: Set git user.signingkey
      git_config:
        name: user.signingkey
        scope: global
        value: "{{ git_signing_key }}"
    - name: Set git commit.gpgsign
      git_config:
        name: commit.gpgsign
        scope: global
        value: "true"
    - name: Add GPG_TTY to ~/.profile
      lineinfile:
        path: "{{ ansible_user_dir }}/.profile"
        line: 'export GPG_TTY=$(tty)'
    - name: Clone Git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "{{ ansible_user_dir }}/workspace/{{ item.directory }}"
        key_file: "{{ ansible_user_dir }}/.ssh/{{ item.key }}"
        update: no
        accept_hostkey: yes
        version: "{{ item.version }}"
      with_items: "{{ git_repos }}"
    - name: Change ownership of any directories set
      become: yes
      file:
        path: "{{ item.directory }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        recurse: "{{ item.recurse }}"
      with_items: "{{ chown_things }}"
